Design System feature option
Orangestack-com/bff-sdui-app-plugin pull request #3
Opened 2022-01-11 17:45 UTC by rodrigofernandozup

Design System feature on BFF SDUI plugin

2022-01-11 17:59 UTC, LG95 requested changes
Please leave in draft or remove `main.py` until the cli v2 embedded python issue is resolved.

2022-01-11 18:01 UTC, LG95 commented on plugin.yml
> +      value: true
```suggestion
      value: true

```

2022-01-11 18:03 UTC, ze12augusto requested changes

2022-01-11 18:10 UTC, LG95 approved these changes

2022-01-11 18:24 UTC, rodrigofernandozup commented on main.py
> +    print("teste main")
tks!!

2022-01-12 12:57 UTC, ze12augusto requested changes

2022-01-12 12:57 UTC, ze12augusto commented on main.py
> +
```suggestion
```

2022-01-12 13:00 UTC, ze12augusto approved these changes

2022-01-20 17:14 UTC, ze12augusto approved these changes

2022-01-20 17:22 UTC, ricardojsilva approved these changes

2022-01-20 17:33 UTC, merged